### ISSUE TITLE
Some problem with p2p-engine

### ISSUE THREAD

**Issue by hoangtrongphuc** [cdnbye/hlsjs-p2p-engine#10]
After used plugin for a while, I faced with some problem: 
- p2p performance not good when ts file has large size. (maybe cause bandwidth of client)
- With difference network, so many time peer A cannot connect to peer B though I used TURN and STUN server. (sometime it's working).
I hope u can have solution for this problems

**Comment by snowinszu** [comment]
1. We are still improving the scheduling algorithm.
2. The connectivity of WebRTC influenced by many factors which is out of our control.

**Comment by snowinszu** [comment]
BTW, how large is the ts size you set?

**Comment by hoangtrongphuc** [comment]
I used 1080 profile for streaming video. The ts size about 3 -> 4MB.
If I test local, it's working fine. But when I connect to difference network, p2p ratio is so low.

**Comment by hoangtrongphuc** [comment]
I think you need to split ts file by multi pieces which can get from peers.

**Comment by snowinszu** [comment]
Do you know the upload bandwidth of these clients?

**Comment by hoangtrongphuc** [comment]
I didn't measure upload bandwidth of these clients. But I sure it's about 3Mbps => 4Mbps

**Comment by snowinszu** [comment]
One solution is getting chunks of data from other peers and then complete the segments by getting other chunks from the CDN. It requires the stream supports CORS, OPTIONS Requests and Range requests.

**Comment by hoangtrongphuc** [comment]
Yes, But It's has a problem because you only can get full .ts file from CDN.
How can you split ts file from CDN ?

**Comment by snowinszu** [comment]
Some CDN support range request of TS to get part of it.
