### ISSUE TITLE
Video won't reproduce with advertisement

### ISSUE THREAD

**Issue by Yokutto** [cdnbye/hlsjs-p2p-engine#12]
Description: I was testing CDNBye with jwplayer + ads and I ended up finding a strange bug, basically when the player is configured with ads (tested with google IMA and VAST) it just does not start, just get a button to give play that has no action. When the player does not find any ads to show, he usually plays.
Seeing the console, I noticed that it has an error related to jwplayer.js: "Error in "beforePlay" event handler: TypeError: Cannot convert undefined or null to object"

**Steps to reproduce:**
1. Go to https://jsfiddle.net/u3Ld2nsw/
2. Open browser console and hit play button
4. See error on console and the video not playing

**Tested with:**
 - OS: Windows
 - Browser: Chrome
 - Version: 67.0.3396.99 (Versão oficial) 64 bits (cohort: Stable)
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)
 - Browser: Microsoft EDGE
 - Version: 42.17134.1.0

I tested it with jwplayer, not sure if this happen to others players

**Comment by snowinszu** [comment]
The main issue here is a bug in the jwplayer.hlsjs.provider.js package, anyone interested in working on fixing this? I will create  a new repository and push the source code later.

**Comment by Yokutto** [comment]
**Just an offtopic question** (I will delete later)
I noticed that sometimes the jwplayer loads the video by default loading (provider.hlsjs.js) and not by the CDNBye HLS (cdnbye@latest). The player loads normally using WebRTC when it is the user's first visit, on the second visit on the same page the jwplayer starts loading with the standard HLS provider. My question is, does CDNbye need to be loaded before, during or after jwplayer.js?

**Comment by Yokutto** [comment]
Sorry but I do not have a good explanation for this. I created an example here: https://www.w3schools.com/code/tryit.asp?filename=FTT2D9X62HDV. Honestly I have no idea why this happens, if you have any ideas please let me know

**Comment by snowinszu** [comment]
@Yokutto  Bug in reproduce with advertisement has been fixed in version 0.2.3, looking forward to your feedback.

**Comment by Yokutto** [comment]
Fixed thanks. Let me know if you have any idea of cdnbye loading that I said up there.

Your work is very appreciated 👍
