### ISSUE TITLE
Video-js

### ISSUE THREAD

**Issue by ash121121** [cdnbye/hlsjs-p2p-engine#13]
Hello is this compatible with the latest video-js 7 ?

kind regards

**Comment by snowinszu** [comment]
Yes, it can theoretically run directly on top of video.js 5.0+. But the  latest video-js 7 hasn't tested yet. 
Looking forward to your feedback.

**Comment by ash121121** [comment]
Seems on all versions im getting a 502 response by cdnbye tracker

**Comment by snowinszu** [comment]
Fixed
