### ISSUE TITLE
User p2p bandwidth speed

### ISSUE THREAD

**Issue by supersh86** [cdnbye/hlsjs-p2p-engine#15]
Hi, tell me how to know the p2p bandwidth speed of the user?

**Comment by snowinszu** [comment]
Do you mean download speed or upload speed?

**Comment by linkec** [comment]
I made some change on the recall
`hls.engine.on('stats', function (data) {
                            var size = hls.engine.fetcher.totalP2PDownloaded;
                            hls.engine.fetcher.totalP2PDownloaded=0;
                            if(size>0){
                                hls.engine.signaler.signalerWs.send({action:'stat',size:size});
                            }
                        })`
then I can receive the P2P downloaded data from signal server.

**Comment by supersh86** [comment]
A funny bug appeared.
If the user uploads the file, then the download information is reduced.

**Comment by snowinszu** [comment]
Please report bug in this way so I can handle it :)
https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by supersh86** [comment]
snowinszu 
This is an example problem from linkec, not all of the code.

**Comment by supersh86** [comment]
snowinszu 
You did not comment on my request(((

**Comment by snowinszu** [comment]
We are developing a system where you can see your bandwidth and PCU.
