### ISSUE TITLE
JWPlayer HLS JS issue

### ISSUE THREAD

**Issue by ranmeo** [cdnbye/hlsjs-p2p-engine#16]
Hi,

When I use your libs with JWPlayer, the JWP control bar always showing up, even with your demo at: http://cdnbye.gitee.io/hlsjs-p2p-engine/jwplayer-demo.html

Could you pls take a look?

Thanks

**Comment by snowinszu** [comment]
Try this:
jwplayer().setControls(false);

**Comment by ranmeo** [comment]
Hi,

I mean, It should be same default: show up on beginning and show off after few seconds, and when mouse over player, it should be showed up again.

 With your suggestion: it's always off..

thanks.

**Comment by afdah** [comment]
I also had the same issue with JWPlayer 8.
With JWPlayer 7, I have no such issue.

**Comment by Yokutto** [comment]
I'm using CDNBye in latest version with jwplayer and i have no issues with controls

**Comment by snowinszu** [comment]
@Yokutto  What version of your jwplayer?

**Comment by Yokutto** [comment]
@snowinszu 8.0.11

**Comment by afdah** [comment]
I believed this is because of jwplayer.hlsjs.provider
[p2p-media-loader](https://github.com/novage/p2p-media-loader) is using [hola](https://github.com/hola/jwplayer-hlsjs) jwplayer.hlsjs.provider. I'm also facing the same issue.

**Comment by snowinszu** [comment]
Yes. Hope someone develop a hlsjs provider for jwplayer 8+.

**Comment by Yokutto** [comment]
I noticed that sometimes after some advertisement that "buffering icon" in the center of the screen does not disappear, even with the video loaded. It's not always that it happens.

**Comment by afdah** [comment]
@ranmeo @Yokutto @snowinszu 
Can you guys check again with the current version v0.3?
It seems to be working again on my end. But I'm on jwplayer v7.12.4

**Comment by snowinszu** [comment]
It is not a formal release.

**Comment by afdah** [comment]
Where you guys got your vast ad provider? It seems this is related to jwplayer vast module.
Maybe I can test? But I'm on JwPlayer 7 though.

**Comment by Yokutto** [comment]
You can use this: https://www.iab.com/insights/vast-2-0-xml-samples-for-testing/
and this: https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

To getting VAST links and test in your player

**Comment by snowinszu** [comment]
Fixed.
