### ISSUE TITLE
tracker service address

### ISSUE THREAD

**Issue by yangshenhuai** [cdnbye/hlsjs-p2p-engine#17]
Hi 

在 ·src/bittorrent/index.js· 中有如下配置 , 请问tracker服务器跟signaler服务器有什么区别? 我们可以向自己部署signaler那样去部署tracker服务器么？ 谢谢.

> let config = {
>     announce: "https://api.cdnbye.com/v1",                           // tracker服务器地址
>     urgentOffset: 3,                                                 // 播放点的后多少个buffer为urgent
> };

**Comment by snowinszu** [comment]
tracker用于节点调度，signaler用于信令交互。
tracker后续会提供docker镜像供自行部署，敬请期待

**Comment by rexerwang** [comment]
> tracker用于节点调度，signaler用于信令交互。
> tracker后续会提供docker镜像供自行部署，敬请期待
大概什么时候呢？

**Comment by snowinszu** [comment]
还在开发中 建议先用现成的服务
