### ISSUE TITLE
Sometimes the tracker does not work.

### ISSUE THREAD

**Issue by supersh86** [cdnbye/hlsjs-p2p-engine#20]
Good day, very often p2p network does not work. There is an induction of the video, and the feasts are not visible.
In the developer tools, I saw that the p2pEngine tree is smaller.
There are no requests to the signaler and the tracker.
This is a valid load
![Imgur](https://i.imgur.com/tT9t3B1.png)
And this load is in error
![Imgur](https://i.imgur.com/FKBhwt6.png)

**Comment by snowinszu** [comment]
Check if ad error.
