### ISSUE TITLE
Idle Peers

### ISSUE THREAD

**Issue by afdah** [cdnbye/hlsjs-p2p-engine#21]
How to have higher number of idle peers?

[https://prnt.sc/kk6a3l](https://prnt.sc/kk6a3l)

Are there any tips? Maybe shorter hls fragments. My hls fragments is currently set at 10s.
Or is there any settings that i can tune within your library?

**Comment by snowinszu** [comment]
It's suggested to reduce hls fragments duration to about 4s.

**Comment by afdah** [comment]
I am trying to write a tracker in php based on [hlsp2p-php-tracker](https://github.com/linkec/hlsp2p-php-tracker).

As you can see below, the 10 peers provided by the tracker is not 'idle.'
What is the logic behind the tracker to provide 'idle' peers to the client?
Maybe you can give me some tips?

[http://prntscr.com/kkd9fw](http://prntscr.com/kkd9fw)

**Comment by snowinszu** [comment]
Tracker do not have a concept of  "idle", you got it wrong.

**Comment by afdah** [comment]
Ok.

Then how do the tracker choose which peers to provide?
From your library, the below data is requested from the peer.

"id"
"device"
"netType"
"host"
"version"
"tag"
"conns"
"failConns"
"errsFragLoad"
"errsBufStalled"
"errsInternalExpt"
"http"
"p2p"

**Comment by snowinszu** [comment]
scheduling by IP.

**Comment by afdah** [comment]
Meaning by location?

**Comment by snowinszu** [comment]
ISP and location
