### ISSUE TITLE
openplayer problem with integration

### ISSUE THREAD

**Issue by supersh86** [cdnbye/hlsjs-p2p-engine#23]
Hello.
I'm trying to integrate cdnbye into a new player.
https://github.com/rafa8626/openplayer
In the description it is said that he has a relationship with mediaelement.

In the settings I use the standard construction:

```
  hls: {
          debug: true,
          p2pConfig: {
              logLevel: 'debug',
           }   
        }
```
HLs has been initialized
![Imgur](https://i.imgur.com/2vBw6O5.png)

And setting p2p is added to the config

![Imgur](https://i.imgur.com/QvXtbIG.png)

But cdnbye did not start

**Comment by snowinszu** [comment]
Could you give me an online demo to test?

**Comment by snowinszu** [comment]
https://docs.cdnbye.com/#/en/players?id=openplayer
