### ISSUE TITLE
那个，我来给你们添加麻烦了

### ISSUE THREAD

**Issue by anglesgirl** [cdnbye/hlsjs-p2p-engine#25]
那个，可以不可以自己的服务器作为转发节点，给点播用户传送资源呢？

m3u8资源都是国外的，wss用国内的好还是国外的好

如果自己弄wss，套上CF，并且做CF优化是否可以呢

CF优化就是不同地方指定不同的CF ip达到最佳效果

**Comment by linkec** [comment]
转发？你说的应该是cdnbye官方所定义的超级P2P节点，作为P2P客户端存在于P2P的网络里，这个可以实现，但是需要自己实现超级P2P节点的程序。wss用国内外无所谓的，只要网络稳定就可以了。我现在正在提供一个免费的信令服务器，可以测试接入，wss://free.freesignal.net。

**Comment by anglesgirl** [comment]
超级节点有教程吗
