### ISSUE TITLE
Connection Timeouts alot

### ISSUE THREAD

**Issue by pavelm89** [cdnbye/hlsjs-p2p-engine#27]
Hi

i would like to know if there are any way to make cdnbye request same segment from 2 or more peers at the same time to avoid all that timouts and get a smooth streaming.
i've set my segment duration to 2 sec and each ts is about 1 to 2 MB but still get timed out and has to download from the HTTP.

is there a way to make this work better or is there any optimization you prefer for a better stream?

is there anything else blocking the peers to exchange data? i see all the peers and connected to them but it times out almost 100% of the time

**Comment by afdah** [comment]
2 sec segment about 1 to 2MB? what quality is the video? 1080p?
i have higher chance of success for smaller size segments.

**Comment by pavelm89** [comment]
yes they are 1080p but even with 720p and 500KB to 1MB it still seems to not work, it works when i oprn 2 tabs and thry send to each other but wont work for other peers, its like they get blocked or something.
is there a firewall i need to configure or ports to open to make it work?

**Comment by afdah** [comment]
Ooh i see. You do not have to configure anything. The signalling server used by the library is there to bypass firewall, blocked ports etc but of course it does not work 100% on complex network.

**Comment by pavelm89** [comment]
then how to make it download 4 to 5 pieces in advance to have enough time to download and not time out?

**Comment by snowinszu** [comment]
Do you use it in live or vod?

**Comment by afdah** [comment]
vod on my end. of course this does not work as well as live.
need to wait for peers watching the same video at the same time than this will work.

**Comment by pavelm89** [comment]
i use it aa VOD too, i have around 10 people on each video all the time but it doeant download anything from them so annoying

**Comment by snowinszu** [comment]
This plugin will pre-download pieces if possible.

**Comment by pavelm89** [comment]
i have my own signaling server but instead it always connects to wss://signal.cdnbye.com/wss

why?

**Comment by pavelm89** [comment]
> > i have my own signaling server but instead it always connects to wss://signal.cdnbye.com/wss
> > why?
> 
> Have you configured?
> 
> ```
>     hlsjsConfig: {
>         debug: false,
>         p2pConfig: {
>             logLevel: 'debug',
>             wsSignalerAddr: 'wss://free.freesignal.net'
>         }
>     },
> ```

yes i did and still shows up as cdnbye signaling server i dont know why

**Comment by snowinszu** [comment]
It may be a bug in the plugin, I will check it later. @pavelm89

**Comment by snowinszu** [comment]
@pavelm89   Could you show me your code?

**Comment by snowinszu** [comment]
This bug is fixed.
