### ISSUE TITLE
fragParsingError

### ISSUE THREAD

**Issue by TheDeadCode** [cdnbye/hlsjs-p2p-engine#32]
**Describe the bug**
Using AES-128 with a HLS adaptive bitrate playlist, 1000 errors per second are thrown:

```
errorType mediaError details fragParsingError errorFatal false
```

Disabling P2P makes the video work.

**To Reproduce**
Contact me via email (REDACTED) so I can host the playlist for you, so you can see the exact issue.

**Expected behavior**
Play the video without throwing an error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 69

**Comment by snowinszu** [comment]
Test this version: https://github.com/cdnbye/hlsjs-p2p-engine/tree/master/dist

**Comment by TheDeadCode** [comment]
Seems to work properly now, although here are the only issues I have noticed:

1. error] > error while initializing DemuxerWorker, fallback on DemuxerInline (I am not sure if that's related).
2. The AAC files are not sent through P2P, but rather by HTTP(S), always.

**Comment by snowinszu** [comment]
1. I am not sure, too.
2. AAC files can not be sent through P2P temporarily.
