### ISSUE TITLE
Need HLS.js p2p for Clappr (help)

### ISSUE THREAD

**Issue by PostMalone** [cdnbye/hlsjs-p2p-engine#36]
Hi , i need some help with getting CDNBye into my clappr code, i cant figure out how to add it...

Here is my code: https://pastebin.com/raw/tga6NRC3

I would appreciate if somebody can add CDNBye plugin.

Thanks

**Comment by snowinszu** [comment]
https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/demo/clappr-demo.html

**Comment by PostMalone** [comment]
> https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/demo/clappr-demo.html

This one works, but do you know how to insert Chromecast plugin and Level selector in this code?

**Comment by snowinszu** [comment]
See Clappr official document
