### ISSUE TITLE
Tracker Server

### ISSUE THREAD

**Issue by cmpxchg16** [cdnbye/hlsjs-p2p-engine#37]
Hi!

First of all I want to thank you on that project 😄 
Second, as part of this project you published the repository of the signaling server, but I don't see the tracker server source code as well.. it's by reason? it's a well known tracker server, or it's your own implementation for that project?
Will glad if you can share a link for it, either yours or generic one.

Thanks!

**Comment by snowinszu** [comment]
There is no plan to open source tracker, you can use our free service :)
