### ISSUE TITLE
Tracker unresponsive

### ISSUE THREAD

**Issue by gvalo** [cdnbye/hlsjs-p2p-engine#39]
First of all, great start on the project. There are some problems here but the biggest issue is the tracker setup. There is some functionality obfuscated away in the package cdnbye-core, which makes it almost impossible to fully debug.

This seems to prevent the implementation of any third party trackers. Which leaves the only solution being your own tracker service. However, this service is inconsistently available and is often returning timeouts and 5xx errors, which prevent playback in some cases ( in others it falls back to http gracefully ).

Secondary tracker issue, is the way in which peers are selected.. the client is receiving the same list of peers every time they are requested, and it doesnt seem to have any kind of targeting.

So this puts the project in a bit of an unusable state. I would suggest either writing a protocol specification so that people can make their own trackers, or some kind of licensing on it if you really need to make money.

What can we do here?
This kind of prevents natural growth of the project in terms of open source development.

**Comment by snowinszu** [comment]
Really thanks for your suggestion. 5xx errors have been fixed. Peers selecting algorithm is under improvement. Lastly, CDNBye is developing towards the commercialization.
