### ISSUE TITLE
Tracker?

### ISSUE THREAD

**Issue by lqkntvn** [cdnbye/hlsjs-p2p-engine#4]
I need make own tracker server and Signal server! Please help me!

**Comment by snowinszu** [comment]
Signal server will open source soon

**Comment by lqkntvn** [comment]
Please share for me Signal server and Tracker via lqkntvn@yahoo.com thank you. I will send beer for you :)

**Comment by hoangtrongphuc** [comment]
Yes, signal and tracker server is so important. They maintain large set of peers in system. How can you group peers by ISP and location, topology for store all peers efficiency ? Please share your experiences. Thank you !

**Comment by lqkntvn** [comment]
In this project the author does not share the signal and tracker server, so we can not actually use it to develop our application. At some point if the author will not free signal and tracker server, then this project will die. We should develop our own project.

**Comment by linkec** [comment]
@lqkntvn You can use IP database to group up Peers by ISP.like ipip.net,maxmind.com.
