### ISSUE TITLE
Cordova 支持

### ISSUE THREAD

**Issue by printfcoder** [cdnbye/hlsjs-p2p-engine#43]
# 现象总结
|运行环境| [官网demo](https://demo.cdnbye.com/)| [源码demo](https://github.com/cdnbye/hlsjs-p2p-engine/tree/master/demo)（运行在本地服务器） |  
|---|---|---|
| Andorid Codorva  |  无法测试 |  运行成功，但是p2p模式未启动 |    
| Andorid Codorva Iframe  | 嵌套测试正常  | 运行成功，但是p2p模式未启动  |    
| Android Brower（常用浏览器）  | 正常  |  运行成功，但是p2p模式未启动 |   
| 桌面浏览器（谷歌）  | 正常  |  运行成功，p2p模式正常启动 |   

# 描述
发现一个有趣的问题，在Cordova环境中访问嵌套贵站的[demo](https://demo.cdnbye.com/)时，p2p模式可以生效，在手机浏览器中也可以。但是使用了源码中的[demo][https://github.com/cdnbye/hlsjs-p2p-engine/tree/master/demo]时，p2p模式没有启用，而是直接访问的cdn。
 
直接使用手机浏览器访问运行了源码中demo的服务也是没有生效，但是同一地址使用桌面浏览器却是可生效的。我的手机浏览器支持webRtc，而且访问[demo](https://demo.cdnbye.com/)也是完全正常。

当我把[demo](https://demo.cdnbye.com/)中的html源码弄下来运行时，发现403异常，想必是refer受到限制。

这方面的文档太少。希望作者抽空解答一下为什么手机浏览器访问源码demo时p2p没工作。

**Comment by snowinszu** [comment]
demo用的p2p插件都是一样的，只是播放器载体不同，你可以用vConsole看下log信息，看看问题出在哪
另外https://demo.cdnbye.com/的url做了防盗链，你可以用自己的流来进行测试
