### ISSUE TITLE
VideoJs (Can't find P2P information in console when using different video source)

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [cdnbye/hlsjs-p2p-engine#45]
I am implementing [http://docs.cdnbye.com/#/en/players?id=videojs](url)
I can see P2P exchange information in console when i use video source as mentioned on demo page but not able to see this information when i change this video source.
Player plays both videos but not showing P2P exchange information in console.

Can you please explain this?

**Comment by zeeshan-ahmad111** [comment]
Is there any specific tool that i should use for this job?

Can you please explain this code logic so far i didn't understand this.

**Comment by snowinszu** [comment]
Can you show your code?
