### ISSUE TITLE
P2P Streaming Logic

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [cdnbye/hlsjs-p2p-engine#47]
I need to know the logic when peers connect to each other.
For example a separate tab(Child tab) opens when i click on "**Create New Peer**".
According to my understanding the first tab always serve as main and other tabs are connecting as child to it and they receive stream from the main tab.

So are child tabs always connected to main and receive stream from it or child tabs also serve as main for other tabs to forward stream?

Can you please clarify this concept.

**Comment by snowinszu** [comment]
Child tabs also serve as main for other tabs, like bittorrent.

**Comment by zeeshan-ahmad111** [comment]
Thanks for your feedback!
How can we know that which child is connected to which parent or other child?
Right now i am not able to understand this concept that which tab is responsible to forward stream to other peer in case of parent and child tabs or vice versa.

**Comment by snowinszu** [comment]
You can listen to the "stats" event which can tell you the traffic uploaded and downloaded.

**Comment by zeeshan-ahmad111** [comment]
Can you please guide me on these questions?
 
1-What happens if the main tab or first parent tab close by user and child tabs are running.
2-What happens with the entry of  new child tab when there is no parent tab.
3-Who will responsible to forward the stream.

**Comment by snowinszu** [comment]
1. Stop getting stream from parent
2. New child will become seeder
3. No one

**Comment by zeeshan-ahmad111** [comment]
Thanks for your feedback!
