### ISSUE TITLE
Big problem with disconnect.

### ISSUE THREAD

**Issue by supersh86** [cdnbye/hlsjs-p2p-engine#49]
Good day.
If the server that broadcasts the video freezes or disconnects from the network, a very scary scenario will start.

The player starts constantly reconnecting to the network, ignoring the settings hls: fragLoadingTimeOut / manifestLoadingTimeOut / levelLoadingTimeOut
In the p2p information in totalP2PDown, the bytes begin to grow, and the RAM and the processor begin to fill with empty information.

Please check this event scenario.

**Comment by snowinszu** [comment]
Hello, could you offer me screenshot or logs?

**Comment by supersh86** [comment]
Yes 
I specifically turned on offline mode to simulate a communication break.

![screenshot 2019-02-18 001.png](https://i.imgur.com/ekQkuIg.png)

**Comment by snowinszu** [comment]
It's a normal request from hls.js, you can replace cdnbye with hls.js and test again.
