### ISSUE TITLE
p2pConfig options

### ISSUE THREAD

**Issue by jersobh** [cdnbye/hlsjs-p2p-engine#5]
Please, can you provide the available p2pConfig options? also, setting logLevel to false is enough? 
Also, what are the optimal settings for HLS (segment length, duration)?
Great lib, thank you so much

**Comment by lovefoodcode** [comment]
1. Can you provide the available p2pConfig options?
https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/docs/English/API.md
2. Setting logLevel to false is enough?
Yes.
3.   What are the optimal settings for HLS?
hls_fragment 3; hls_playlist_length 60; （For reference only.）

**Comment by jersobh** [comment]
Thank you so much!
