### ISSUE TITLE
cannot sign up here https://oms.cdnbye.com/#/signup

### ISSUE THREAD

**Issue by mdellanave** [cdnbye/hlsjs-p2p-engine#50]
Hi, I cannot get the code to proceed with the sign up process.
After entering my email address and clicking the send button I see a 10000ms timeout exception.

I would like to register to try my player (custom but based on hls.js)

thanks for your attention

**Comment by snowinszu** [comment]
Please change your email address and try again

**Comment by mdellanave** [comment]
uhm are you sure?
I tried different email addresses but all with the same result
"timeout of 10000ms exceeded"

**Comment by snowinszu** [comment]
which email do you use? gmail is ok

**Comment by mdellanave** [comment]
I tried with a gmail account and also with my corporate email but in both cases I had a timeout exception.
When I press the send button I see a call to https://cgi.cdnbye.com:6067/v1/vcode; nothing happens but the timeout exception message.

**Comment by snowinszu** [comment]
Send your email address to service@cdnbye.com

**Comment by mdellanave** [comment]
Ok thanks, I just sent the email
