### ISSUE TITLE
backend can not create the .club domain

### ISSUE THREAD

**Issue by Glorydaqin** [cdnbye/hlsjs-p2p-engine#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/12810067/53396116-9cefe080-39de-11e9-9b1b-6d18d4c8f1ee.png)

**Comment by snowinszu** [comment]
Please try again.

**Comment by Androidliguo** [comment]
may be you should add the domain like this  ----https://www.deephd.club @Glorydaqin
