### ISSUE TITLE
errorType mediaError details bufferAppendError errorFatal true reason undefined

### ISSUE THREAD

**Issue by fredyzhang5532** [cdnbye/hlsjs-p2p-engine#57]
当切换视频后，视频正常播放，但是显示
chrome console显示
**errorType mediaError details bufferAppendError errorFatal true reason undefined**
然后p2p就停止了，没有任何打印输出了
OS win10 chrome

**Comment by snowinszu** [comment]
你好，
    请提供可以测试的地址，或者加QQ：86755838
