### ISSUE TITLE
How to integrate with playerjs.com

### ISSUE THREAD

**Issue by tortoros** [cdnbye/hlsjs-p2p-engine#58]
We use player https://playerjs.com/en/

How to integrate p2p-media-loader with this player?

**Comment by snowinszu** [comment]
1. Disable the HLS plugin in the builder
2. Place cdnbye script tag on the page before playerjs.
For example:
<div id="player"></div>
<script src="https://cdn.jsdelivr.net/npm/cdnbye@latest"></script>
<script src="./playerjs.js" type="text/javascript"></script>
<script>
    var player = new Playerjs({id:"player", file:"https://example.m3u8"});
</script>
