### ISSUE TITLE
Signaling server

### ISSUE THREAD

**Issue by jersobh** [cdnbye/hlsjs-p2p-engine#8]
Hi there,

I guess that the signaling server will not be open sourced, right? 

Thanks, and great job!

**Comment by snowinszu** [comment]
Signaling server will open source soon, it's written by Go. But I haven't enough time to write document, hope someone help to maintain it together.

**Comment by jersobh** [comment]
You can count on me :)

**Comment by snowinszu** [comment]
That's great!

**Comment by snowinszu** [comment]
@jersobh  https://github.com/cdnbye/gosignaler

**Comment by jersobh** [comment]
Great! Thank you :)

Em sáb, 7 de jul de 2018 11:31, snowinszu <notifications@github.com>
escreveu:

**Comment by phillipseamore** [comment]
On a related note - can we expect to see the tracker as well?  I thought the project was using webtorrent/bittorrent-tracker but in my tests it hasn't been working.

**Comment by snowinszu** [comment]
Tracker is under development, using protocols different from webtorrent/bittorrent-tracker.

**Comment by linkec** [comment]
@snowinszu Any EST on Tracker?
