### ISSUE TITLE
ABR stream with level in URL

### ISSUE THREAD

**Issue by phillipseamore** [cdnbye/hlsjs-p2p-engine#9]
Hi,

I'm testing with ABR streams where levels are done in folders like:
```
http://DOMAIN/live/streamname/tracks-v1a1/2018/07/06/18/28/46-10000.ts
http://DOMAIN/live/streamname/tracks-v2a1/2018/07/06/18/28/46-10000.ts
http://DOMAIN/live/streamname/tracks-v3a1/2018/07/06/18/28/46-10000.ts
http://DOMAIN/live/streamname/tracks-v4a1/2018/07/06/18/28/46-10000.ts
```
The playlist contain relative URL's:
`/2018/07/06/18/28/46-10000.ts`

This means segments are shared for different levels and HLS displays them incorrectly.

I can't change the URL's or the playlists to be absolute URL's.

Could hlsjs-p2p-engine be extended to also look at the level HLS is using?

**Comment by lovefoodcode** [comment]
Can hls.js display your streams correctly?

**Comment by phillipseamore** [comment]
Hls.js displays them correctly and switches between bitrates without problems.

To explain further, if we have a browser streaming level 1 and a browser streaming level 4, one of them will send "/2018/07/06/18/28/46-10000.ts" to the other but it will of course not be the correct stream.

**Comment by snowinszu** [comment]
Could you give me your m3u8 to test?

**Comment by snowinszu** [comment]
Try to set this option:
p2pConfig: {
        tsStrictMatched: true,                             
    }

**Comment by phillipseamore** [comment]
tsStrichMatched does not change the behavior - I think it only strips query parameters.

The streams I work with are all locked down - but here is a stream that behaves the same:
https://dailyblackmail.com/bbb/index.m3u8

Also here is a test player with Clappr and level selector, it can help to force the player that is supplying the segments to a different level and then it changes the segments on the slave player:
https://dailyblackmail.com/bbb/cdnbye.html

I think we need to advertise the segments with the complete path (not complete URL since domains might not match in a multi server situation).

On a related note I'd also like to recommend adding an optional ID to the p2pconfig so that it's possible to configure the ID of the stream.   P2Pconfig has "id: thisisanid" and only clients with the same id would share segments.  (This does not however solve the ABR level problem here).

**Comment by phillipseamore** [comment]
Done some testing and everything works perfectly.  Thanks for the very quick response!
